### ISSUE TITLE
Error when trying to run integration content repository

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#148]
**Describe the bug**
When trying to run `docker run` for the docker image on hub.docker the following error occurs:

```json
docker run openintegrationhub/integration-content-repository
module.js:549
    throw err;
    ^

Error: Cannot find module '/usr/src/app/server.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**To Reproduce**
1. docker pull openintegrationhub/integration-content-repository
2. Set up & run MongoDB
3. Run OIH/IAM
4. docker run openintegrationhub/integration-content-repository

**Expected behavior**
Service starts without errors.

**Additional context**
Error occurs on `Windows` and `Linux`.
Problem is already known by teamlead - Issue is just for tracking reasons.

**Comment by philecs** [comment]
Fixed with merge of #152
