### ISSUE TITLE
ICR get all flows throws error

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#158]
**Describe the bug**
Cannot receive all flows from ICR API

**To Reproduce**
1. Authorize with IAM token
2. Try out get all flows

**Expected behavior**
All flows received.

**Screenshots**
```
[2018-12-03T10:57:57.341Z] DEBUG: app/3432 on DESKTOP-5M29AFL (C:\Users\xxx\openintegrationhub\services\integration-content-repository\app\api\controllers\mongo.js:66 in Flow.find.sort.skip.limit.lean.then.catch): $and/$or/$nor must be a nonempty array
  MongoError: $and/$or/$nor must be a nonempty array
      at queryCallback (C:\Users\xxx\openintegrationhub\services\integration-content-repository\node_modules\mongodb-core\lib\cursor.js:248:25)
      at C:\Users\xxx\openintegrationhub\services\integration-content-repository\node_modules\mongodb-core\lib\connection\pool.js:532:18
      at process._tickCallback (internal/process/next_tick.js:112:11)

```
**Additional context**

**Comment by SvenHoeffler** [comment]
This most likely happened during the switch to the Owner array. Currently investigating.
