### ISSUE TITLE
502 when making bulk import request

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#641]
**Describe the bug**
While trying to bulk import a zip file the service was eliminated and a 502 error code was thrown.

```console
Error: Part terminated early due to unexpected end of multipart data at /tmp/node_modules/dicer/lib/Dicer.js:65:36 at _combinedTickCallback (internal/process/next_tick.js:131:7) at process._tickCallback (internal/process/next_tick.js:180:9)
```

**To Reproduce**
1. Perform the following request:

```json
form.append('archive', data);
const uploadBulk = {
    method: 'POST',
    uri: `http://metadata.openintegrationhub.com/api/v1/domains/${domainID}/schemas/import`,
    headers: {
        "Authorization" : " Bearer " + tokenAdmin,
        "Content-Type": `multipart/form-data`,
    },
    formData: {
        name: 'archive',
        file: form
    }
};
const response = await request(uploadBulk);
```

**Expected behavior**
Zip uploaded. Metadata responds with 200 status code and response body 'OK'.

**Screenshots**

![image.png](https://images.zenhubusercontent.com/597889db61b4ca3b0a75bf15/d207c04c-3880-4686-abba-b6c7a054d4f4)

**Additional context**

**Comment by philecs** [comment]
Error still present:

**Response from console.log:**

```
{"statusCode":502,"body":"\n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>502 Server Error</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Server Error</h1>\n<h2>The server encountered a temporary error and could not complete your request.
```

**K8s Logs:**

```
2019-08-14 14:54:22.772 CEST
RangeError: Invalid status code
```

**Comment by philecs** [comment]
Fixed and tested
