### ISSUE TITLE
Event Bus throws uncaught exception when attempting to disconnect

### ISSUE THREAD

**Issue by SvenHoeffler** [openintegrationhub/openintegrationhub#747]
**Describe the bug**
When using the `disconnect()` function of an instance of the EventBus class that has already connected to a queue, the following exception is thrown:

```
{"name":"sdf-adapter","hostname":"sven-Notebook","pid":29280,"level":50,"err":{"message":"Channel ended, no reply will be forthcoming","name":"Error","stack":"Error: Channel ended, no reply will be forthcoming
at rej (/home/sven/Desktop/openintegrationhub/services/dispatcher-service/node_modules/@openintegrationhub/event-bus/node_modules/amqplib/lib/channel.js:190:7
at Channel.Object.<anonymous>.C._rejectPending (/home/sven/Desktop/openintegrationhub/services/dispatcher-service/node_modules/@openintegrationhub/event-bus/node_modules/amqplib/lib/channel.js:192:28)
at Channel.Object.<anonymous>.C.toClosed (/home/sven/Desktop/openintegrationhub/services/dispatcher-service/node_modules/@openintegrationhub/event-bus/node_modules/amqplib/lib/channel.js:160:8)
at Connection.Object.<anonymous>.C._closeChannels (/home/sven/Desktop/openintegrationhub/services/dispatcher-service/node_modules/@openintegrationhub/event-bus/node_modules/amqplib/lib/connection.js:393:18)
at Connection.Object.<anonymous>.C.toClosed (/home/sven/Desktop/openintegrationhub/services/dispatcher-service/node_modules/@openintegrationhub/event-bus/node_modules/amqplib/lib/connection.js:400:8)
at Connection.accept (/home/sven/Desktop/openintegrationhub/services/dispatcher-service/node_modules/@openintegrationhub/event-bus/node_modules/amqplib/lib/connection.js:379:12)
at Socket.go (/home/sven/Desktop/openintegrationhub/services/dispatcher-service/node_modules/@openintegrationhub/event-bus/node_modules/amqplib/lib/connection.js:477:48)
at Socket.emit (events.js:189:13)
at emitReadable_ (_stream_readable.js:535:12)
at process._tickCallback (internal/process/next_tick.js:63:19)"},"msg":"Channel ended, no reply will be forthcoming","time":"2019-09-11T08:47:15.425Z","v":0}
```

**To Reproduce**
1. Instantiate an instance of the Event Bus:
```
const logger = bunyan.createLogger({ name: 'dispatcher-service' });
const transport = new RabbitMqTransport({ rabbitmqUri: config.amqpUrl, logger });
const eventBus = new EventBus({ transport, logger, serviceName: 'dispatcher-service' });
```

2. Call its connect() function:
```
await eventBus.connect();
```

3. Call its disconnect() function:
```
await eventBus.disconnect()
```

**Expected behavior**
The eventbus should successfully disconnect without throwing an exception.

**Comment by SvenHoeffler** [comment]
This appears to be a race condition that can occur when a connection is disconnected too soon after being connection. The event bus is still in progress of creating the channel from the `connect` function call while also attempting to close it again for the `disconnect` call. 

Easiest solution/workaround is to make certain these functions are not called immediately after one another. A delay of at around ~50ms appears to be sufficient.
