### ISSUE TITLE
Component Orchestrator error

### ISSUE THREAD

**Issue by mlb5000** [openintegrationhub/openintegrationhub#925]
When trying to launch my first Flow, the K8S logs for `component-orchestrator` show that it's running into an error. This is just for one of the 3 nodes in my flow graph, but the same error happens for each of them.

```
  {
    "name": "component-orchestrator",
    "hostname": "component-orchestrator-7bb74579dc-dpvpw",
    "pid": 29,
    "level": 30,
    "flow": "5e2cab4e822fa0001b7b64ff",
    "msg": "Going to deploy job to k8s",
    "time": "2020-01-25T21:33:15.952Z",
    "v": 0
  }
  {
    "name": "component-orchestrator",
    "hostname": "component-orchestrator-7bb74579dc-dpvpw",
    "pid": 29,
    "level": 20,
    "secretName": "5e2cab4e822fa0001b7b64ffstep2",
    "msg": "About to create a secret",
    "time": "2020-01-25T21:33:15.962Z",
    "v": 0
  }
  {
    "name": "component-orchestrator",
    "hostname": "component-orchestrator-7bb74579dc-dpvpw",
    "pid": 29,
    "level": 50,
    "err": {
      "message": "The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined",
      "name": "TypeError [ERR_INVALID_ARG_TYPE]",
      "stack": "TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined\n    at Function.from (buffer.js:207:11)\n    at toBase64 (/usr/lib/component-orchestrator/services/component-orchestrator/src/drivers/kubernetes/FlowSecret.js:3:32)\n    at data.Object.entries.reduce (/usr/lib/component-orchestrator/services/component-orchestrator/src/drivers/kubernetes/FlowSecret.js:44:29)\n    at Array.reduce (<anonymous>)\n    at FlowSecret.toDescriptor (/usr/lib/component-orchestrator/services/component-orchestrator/src/drivers/kubernetes/FlowSecret.js:42:45)\n    at KubernetesDriver._createFlowNodeSecret (/usr/lib/component-orchestrator/services/component-orchestrator/src/drivers/kubernetes/KubernetesDriver.js:83:30)\n    at KubernetesDriver._ensureFlowNodeSecret (/usr/lib/component-orchestrator/services/component-orchestrator/src/drivers/kubernetes/KubernetesDriver.js:37:25)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
      "code": "ERR_INVALID_ARG_TYPE"
    },
    "msg": "Failed to deploy the job",
    "time": "2020-01-25T21:33:15.962Z",
    "v": 0
  }
```

I instrumented the code a little bit so I could get some logging output at that point, and got the following output:

```
  {
    "name": "5e2cab4e822fa0001b7b64ffstep3",
    "hostname": "component-orchestrator-649c97d47f-t79w9",
    "pid": 29,
    "level": 20,
    "msg": "FlowSecret.toDescriptor: key: ELASTICIO_USER_ID, value: undefined",
    "time": "2020-01-25T22:23:34.433Z",
    "v": 0
  }
  {
    "name": "component-orchestrator",
    "hostname": "component-orchestrator-649c97d47f-t79w9",
    "pid": 29,
    "level": 50,
    "err": {
      "message": "The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined",
      "name": "TypeError [ERR_INVALID_ARG_TYPE]",
      "stack": "TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined\n    at Function.from (buffer.js:207:11)\n    at toBase64 (/usr/lib/component-orchestrator/services/component-orchestrator/src/drivers/kubernetes/FlowSecret.js:3:32)\n    at data.Object.entries.reduce (/usr/lib/component-orchestrator/services/component-orchestrator/src/drivers/kubernetes/FlowSecret.js:47:29)\n    at Array.reduce (<anonymous>)\n    at FlowSecret.toDescriptor (/usr/lib/component-orchestrator/services/component-orchestrator/src/drivers/kubernetes/FlowSecret.js:42:45)\n    at KubernetesDriver._createFlowNodeSecret (/usr/lib/component-orchestrator/services/component-orchestrator/src/drivers/kubernetes/KubernetesDriver.js:83:30)\n    at KubernetesDriver._ensureFlowNodeSecret (/usr/lib/component-orchestrator/services/component-orchestrator/src/drivers/kubernetes/KubernetesDriver.js:37:25)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
      "code": "ERR_INVALID_ARG_TYPE"
    },
    "msg": "Failed to deploy the job",
    "time": "2020-01-25T22:23:34.433Z",
    "v": 0
  }
```

Somehow the `USER_ID` value (read here: https://github.com/openintegrationhub/openintegrationhub/blob/master/services/component-orchestrator/src/drivers/kubernetes/KubernetesDriver.js#L203) is `undefined` for this flow. I'm going to see if stopping and starting the flow will fix anything.

**Comment by mlb5000** [comment]
Nope, recreating the flow doesn't fix anything, `USER_ID` is still `undefined`

**Comment by mlb5000** [comment]
As is `IAM_TOKEN`, though I suspect what it believes to be `envVars` are not actually coming from the environment, but the RabbitMQ message passed down from `component-orchestrator` here: https://github.com/openintegrationhub/openintegrationhub/blob/master/lib/component-orchestrator/src/ComponentOrchestrator.js#L87

The `settings` variable passed to `createApp` comes from the `RabbitMqQueuesManager` here: https://github.com/openintegrationhub/openintegrationhub/blob/0c4275386fdec2d0cb2006732c3a8d5f3be96452/services/component-orchestrator/src/queues-manager/RabbitMqQueuesManager.js#L33, which fills in `AMQP_URI`, but not `IAM_TOKEN`.

**Comment by RobinBrinkmann** [comment]
@pnedelko & @sachmerz  maybe you can help.

**Comment by mlb5000** [comment]
One more thing :). When you create a flow in the `inactive` state, the Orchestrator spits out errors regarding configuration on this same code path in `FlowSecret.js`, but on a different environment variable:

```
{
  "name": "component-orchestrator",
  "hostname": "component-orchestrator-ffc57649c-kwbqf",
  "pid": 29,
  "level": 50,
  "err": {
    "message": "The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object",
    "name": "TypeError [ERR_INVALID_ARG_TYPE]",
    "stack": "TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object\n    at Function.from (buffer.js:232:9)\n    at toBase64 (/usr/lib/component-orchestrator/services/component-orchestrator/src/drivers/kubernetes/FlowSecret.js:3:32)\n    at data.Object.entries.reduce (/usr/lib/component-orchestrator/services/component-orchestrator/src/drivers/kubernetes/FlowSecret.js:45:33)\n    at Array.reduce (<anonymous>)\n    at FlowSecret.toDescriptor (/usr/lib/component-orchestrator/services/component-orchestrator/src/drivers/kubernetes/FlowSecret.js:42:45)\n    at KubernetesDriver._createFlowNodeSecret (/usr/lib/component-orchestrator/services/component-orchestrator/src/drivers/kubernetes/KubernetesDriver.js:83:30)\n    at KubernetesDriver._ensureFlowNodeSecret (/usr/lib/component-orchestrator/services/component-orchestrator/src/drivers/kubernetes/KubernetesDriver.js:37:25)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
    "code": "ERR_INVALID_ARG_TYPE"
  },
  "msg": "Failed to convert to base64 key: ELASTICIO_COMP_ID, value: 5e2c8d9388045e001d14c2f8, type: object",
  "time": "2020-01-27T14:06:56.100Z",
  "v": 0
}
```

I added the log output here, and strangely the message reports that **somehow**, the string `5e2c8d9388045e001d14c2f8` in the `COMP_ID` field of the RabbitMQ message is considered an `object` by the `typeof` operator...

Log message:
```
logger.error(e, `Failed to convert to base64 key: ${key}, value: ${value}, type: ${typeof value}`);
```

**Comment by mlb5000** [comment]
BTW, I fixed the last issue regarding `COMP_ID` not being a "string", by literally just calling `.toString()` on it here:

https://github.com/openintegrationhub/openintegrationhub/blob/486782e419ab548be4ee85abd8f29a6342cd9ed2/services/component-orchestrator/src/drivers/kubernetes/KubernetesDriver.js#L204

**Comment by mlb5000** [comment]
This issue was resolved by https://github.com/openintegrationhub/openintegrationhub/commit/dda82027af68443f2da498c50ccb6d0288343ad9
