### ISSUE TITLE
Local setup of OIH: Can't create domains in metdata repository

### ISSUE THREAD

**Issue by tboehle** [openintegrationhub/openintegrationhub#939]
**Describe the bug**
A domain for the metadata repository can't be created via postman or the Swagger UI. 
For the Swagger UI this is caused by a wrong configuration: The Swagger UI points to the server `http://metadata.openintegrationhub.com/api/v1/domains` instead of `http://metadata.localoih.com/api/v1/domains`

Via postman I am just getting this error returned:
```json
{
    "message": "Error"
}
```
The log of the metadata repository pod of my kubernetes node displays:
```txt
[31merror[39m:  StatusCodeError: 404 - "Not Found"
    at new StatusCodeError (/tmp/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/tmp/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/tmp/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/tmp/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/tmp/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/tmp/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
[31merror[39m: Token not found in IAM 
{ introspectType: [32m'basic'[39m,
  token: [32m'hwzXPtpHQ9noBtiz9qwrG1r1yxGY5jJ-_9pyJlIKWVIKwVcJ_PfziALkXxKl5wX3aqtJHF3w32F1rcGav_gOnQkPBpajbegYgZJw-ATldsLX5zXX-5nwebQ7eKdoGLXnRumUfLkiWOlI9_hWXvkBmLPMMpzn_J3fxw0KLJrPaJE'[39m,
  logger: [32m'iam-middleware'[39m }
[31merror[39m:  StatusCodeError: 404 - "Not Found"
    at new StatusCodeError (/tmp/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/tmp/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/tmp/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/tmp/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/tmp/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/tmp/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
[31merror[39m: Token not found in IAM 
{ introspectType: [32m'basic'[39m,
  token: [32m'aWtHNTAtaS03STgzek82S0REVkdhdC1Ham0zcDdNSzkzZXVvNjM3ckk3YUU2NVItMGwzUXl6S0pnQmJ6S1djLWN0dTIzWnVIZFZndDhQWVZZT3gxZlFlX2xleWpMMnlpVUF3RXUzdDVfbmlvNXVoaE1nNk4yeG4zNW5YekM3OEx1YjBBMWxmNW9xWi16c3ZsZ2hmMktyZEJuTkU4NTNzTzdMRnlDZHp2M3Vz'[39m,
  logger: [32m'iam-middleware'[39m }
[33mwarn[39m: currentContext is deprecated. Rely on user.tenant instead. 
{ logger: [32m'iam-middleware'[39m }
```
I tried the request with my admin token as well with my service account token, but the error remained.

Also via the Web-UI I didn't find docs on how to create a domain via the UI or which values I have to provide that the Web-UI dialog recognizes it should call the domain api route. Codewise the action is there for the Web-UI: `services/web-ui/src/action/metadata.js`
Did I miss the correct docs?

**To Reproduce**
My postman request looks like:
* My request URL is `http://metadata.localoih.com/api/v1/domains`
* admin token as bearer token
* request body:
```json
{
  "name": "PITERION",
  "description": "Domain for all PITERION data models",
  "public": true,
  "owners": [
    {
      "id": "5e68aecb5ea1360011dbf562",
      "type": "user"
    }
  ]
}
```
Over the Web-UI I only see these fields:
```yaml
{
  name: 'String',
  description: 'string',
  public: true,
  owners: [
    {
      id: '5e68aecb5ea1360011dbf562',
      type: 'USER'
    }
  ]
}
```
Also the [docs](https://openintegrationhub.github.io/docs/Services/MetaDataRepository.html) didn't help me. Where is the option to give the type of my object, either a domain or a data model?

**Expected behavior**
The domain should be created in the metadata repository or there should be a more detailled error message.
Also in the Web-UI I should have some options to provide the target type of my object

**Additional context**
It's a local setup over a minikube virtualbox VM.

Thanks for any help in in advance

**Comment by blaggacao** [comment]
fyi &mdash; I'm currently working on a better devops handel onto the deployment manifests at #1041 this exposes the domein configuration more compact which should help spot such inconsitencies earlier and more reliably.

**Comment by RobinBrinkmann** [comment]
In the process of streamlining the framework, the Meta Data Repository will soon be moved out of the monorepo. It will be kept in a separate repository as a reference and for anyone who wants to continue work on it. There will not be any maintenance by the core dev team.
