### ISSUE TITLE
Webhooks - Trigger execution fails at node

### ISSUE THREAD

**Issue by mlb5000** [openintegrationhub/openintegrationhub#993]
Using the latest version of the `Webhooks` service on master (which seems to be required with the newer services, otherwise it seems to think all Flows are either inactive or missing)

1. Trigger as webhook as some authenticated user `GET hook/{flowId}`
1. Step in the corresponding flow ends up with the error:

```
Invalid message headers: AssertionError [ERR_ASSERTION]: UserId is missing in message header
    at Sailor.readIncomingMessageHeaders (/usr/src/app/node_modules/elasticio-sailor-nodejs/lib/sailor.js:117:9)
    at Sailor.processMessage (/usr/src/app/node_modules/elasticio-sailor-nodejs/lib/sailor.js:158:43)
    at decryptMessage (/usr/src/app/node_modules/elasticio-sailor-nodejs/lib/amqp.js:82:17)
    at Channel.BaseChannel.dispatchMessage (/usr/src/app/node_modules/amqplib/lib/channel.js:466:12)
    at Channel.BaseChannel.handleDelivery (/usr/src/app/node_modules/amqplib/lib/channel.js:475:15)
    at Channel.emit (events.js:315:20)
    at Channel.EventEmitter.emit (domain.js:483:12)
    at /usr/src/app/node_modules/amqplib/lib/channel.js:263:10
    at Channel.content [as handleMessage] (/usr/src/app/node_modules/amqplib/lib/channel.js:316:9)
    at Channel.C.acceptMessageFrame (/usr/src/app/node_modules/amqplib/lib/channel.js:231:31)
    at Channel.C.accept (/usr/src/app/node_modules/amqplib/lib/channel.js:384:17)
    at Connection.mainAccept [as accept] (/usr/src/app/node_modules/amqplib/lib/connection.js:63:33)
    at Socket.go (/usr/src/app/node_modules/amqplib/lib/connection.js:476:48)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at emitReadable_ (_stream_readable.js:555:12)
```

This was not an issue with the version of Webhooks we were using previously.

**Comment by mlb5000** [comment]
OK, it looks like `EventBus` is packaging the entire `Event` as the body to send across the channel, without sending `msgOpts` into `ampqlib.publish`. Whereas Flow Nodes appear to expect the body to be the equivalent of `Event.payload.msg` and Options to be `Event.payload.msgOpts`. Similar to #985, this breaks compatibility with Sailor component nodes.

**Comment by RobinBrinkmann** [comment]
Hi Matthew, sorry for the hick-ups right now. We are currently making some major changes, which include re-writing the sailor and a new version of the component orchestrator.  Thank you for your feedback, which really helps us to identify where some rework is necessary. 
@SvenHoeffler & @sachmerz please check.

**Comment by heggert** [comment]
Hi, i will have a look today. Thanks for opening the PRs

**Comment by heggert** [comment]
I approved 

https://github.com/openintegrationhub/openintegrationhub/pull/987
https://github.com/openintegrationhub/openintegrationhub/pull/988
https://github.com/openintegrationhub/openintegrationhub/pull/990
https://github.com/openintegrationhub/openintegrationhub/pull/994
https://github.com/openintegrationhub/openintegrationhub/pull/995

### Some notes to PR https://github.com/openintegrationhub/openintegrationhub/pull/986

We changed the way components talk to each other.

Before those changes, a component published a message directly to the queue of a subsequent component.

Now every component publishes to the same **backchannel queue** where the component orchestrator is listening on. After receiving a message, orchestrator publishes to the next component.

We could stay with the old naming "PUBLISH_MESSAGES_TO" but it would still break... Because we did another major change to make everything more dynamic: An **orchestratorToken** now holds needed information to execute an action/trigger and is passed within the messages record. 

We ended up replacing and reworking functionality of **sailor** to have a match with our new requirements: **Ferryman** will compensate (https://github.com/openintegrationhub/openintegrationhub/tree/master/lib/ferryman) and serve as a new coponent lib.

I don't know your specific setup but i fairly recommend to switch component libs as soon as it gets stable.

Right now we are at a "testing phase". So expect things to break... :)

Thanks for your help! If you have any further questions, I'll be happy to help, just write to me via slack
